[package]
name = "remove-query-string"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = { workspace = true, features = ["html_reports"] }

[[bench]]
name = "benchmark_by_time"
harness = false
