
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.aho-corasick]]
version = "1.1.2"
criteria = "safe-to-run"

[[exemptions.anstyle]]
version = "1.0.5"
criteria = "safe-to-run"

[[exemptions.bincode]]
version = "1.3.3"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "2.4.2"
criteria = "safe-to-run"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.clang-sys]]
version = "1.7.0"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "4.4.18"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.4.18"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.5"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.19"
criteria = "safe-to-run"

[[exemptions.half]]
version = "2.3.1"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.home]]
version = "0.5.9"
criteria = "safe-to-run"

[[exemptions.iai]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.iai-callgrind]]
version = "0.10.2"
criteria = "safe-to-run"

[[exemptions.iai-callgrind-macros]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.iai-callgrind-runner]]
version = "0.10.2"
criteria = "safe-to-run"

[[exemptions.is-terminal]]
version = "0.4.10"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.67"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.153"
criteria = "safe-to-run"

[[exemptions.libloading]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.linux-raw-sys]]
version = "0.4.13"
criteria = "safe-to-run"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.nom]]
version = "7.1.3"
criteria = "safe-to-run"

[[exemptions.plotters]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.prettyplease]]
version = "0.2.16"
criteria = "safe-to-run"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.78"
criteria = "safe-to-run"

[[exemptions.regex]]
version = "1.10.3"
criteria = "safe-to-run"

[[exemptions.regex-automata]]
version = "0.4.5"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.8.2"
criteria = "safe-to-run"

[[exemptions.rustix]]
version = "0.38.30"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.16"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.196"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.196"
criteria = "safe-to-run"

[[exemptions.serde_json]]
version = "1.0.113"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.48"
criteria = "safe-to-run"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.walkdir]]
version = "2.4.0"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.90"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.90"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.90"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.90"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.90"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.67"
criteria = "safe-to-run"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-util]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.0"
criteria = "safe-to-run"
