name: benchmark
on:
  push:
  # branches:
  # - main
  pull_request:
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  # setup sccache for Rust; see https://github.com/Mozilla-Actions/sccache-action
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
jobs:
  iai:
    if: false # iai is always failed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          shared-key: "${{ github.workflow }}"

      - uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11

      - run: rustup default stable

      - run: sudo apt-get -y install valgrind
      - run: cargo bench -p remove-query-string --bench benchmark_by_cachegrind

  gungraun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          shared-key: "${{ github.workflow }}"

      - uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11

      - run: rustup default stable

      - run: sudo apt-get -y install valgrind

      - uses: taiki-e/install-action@065d6a08a14e61e89fb0a4c10eecdbdef39c7d8e # v2.85.4
        with:
          tool: cargo-binstall

      - name: Install gungraun-runner
        run: |
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "gungraun").version' |\
            tr -d '"'
          )
          # --force is needed;
          # otherwise, it reports gungraun-runner installed already incorrectly
          # and skip installation
          cargo binstall --no-confirm gungraun-runner --force --version $version

      - run: cargo bench -p remove-query-string --bench benchmark_by_callgrind
